# Numpy array

In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
# matrix
np.array([[1,2,3],[1,2,5]])

array([[1, 2, 3],
       [1, 2, 5]])

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [9]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [12]:
np.linspace(1,10,4) # evenly spaced numbers

array([  1.,   4.,   7.,  10.])

In [13]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [15]:
np.random.rand(5,5) # random between 0 and 1

array([[ 0.10561125,  0.5947363 ,  0.91658017,  0.82284441,  0.93917107],
       [ 0.14875727,  0.02841923,  0.70564175,  0.81984507,  0.67292042],
       [ 0.8278234 ,  0.52606879,  0.58276744,  0.29146479,  0.72522443],
       [ 0.22439093,  0.81770339,  0.18628285,  0.69647342,  0.42006847],
       [ 0.18617321,  0.98073186,  0.73038614,  0.0146186 ,  0.64271335]])

In [16]:
np.random.randn(2) # Gaussian distribution

array([-0.05164294,  0.255733  ])

In [19]:
rarr = np.random.randint(0,10, 10)

In [20]:
rarr

array([2, 8, 5, 9, 1, 1, 7, 1, 7, 7])

In [23]:
rarr.reshape(2,5)

array([[2, 8, 5, 9, 1],
       [1, 7, 1, 7, 7]])

In [24]:
rarr

array([2, 8, 5, 9, 1, 1, 7, 1, 7, 7])

In [25]:
rarr.max()

9

In [26]:
rarr.min()

1

In [27]:
rarr.argmax() # returns index

3

In [28]:
rarr.shape

(10,)

In [29]:
rarr = rarr.reshape(2,5)

In [30]:
rarr.shape

(2, 5)

In [31]:
rarr.dtype

dtype('int64')

# Numpy array indexing

In [32]:
rarr[1]

array([1, 7, 1, 7, 7])

In [36]:
arr = np.random.randint(1,10,10)    

In [37]:
arr[0]

4

In [38]:
arr

array([4, 6, 3, 9, 8, 9, 7, 6, 1, 5])

In [39]:
# Broadcast
arr[5:] = 100

In [40]:
arr

array([  4,   6,   3,   9,   8, 100, 100, 100, 100, 100])

In [41]:
arr = arr.reshape(2,5)

In [43]:
arr[1,4] # indexing 2d array

100

In [44]:
bool_arr = arr > 10 # boolean array for conditionally select

In [45]:
bool_arr

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True]], dtype=bool)

# Salar operations

In [50]:
arr = np.arange(0,10)

In [51]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91])

In [53]:
arr / arr # only warning

/home/dalonlobo/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [54]:
np.log(arr)

/home/dalonlobo/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

In [55]:
# Check universal functions